### ISSUE TITLE
Symbols not displaying in web app

### ISSUE THREAD

**Issue by pt-rick** [timmaffett/material_symbols_icons#11]
Was thrilled to find your package as there are multiple Material icons I found missing in the standard Flutter Icons. Thank you! 

When I attempt to use Symbols in a web app, they appear as rectangles with an ‘x - likely standard for a missing IconData? You can see the Symbol icons below the regular Flutter Icons attached. Everything looks fine on my Android Flutter app BTW.

![image](https://github.com/timmaffett/material_symbols_icons/assets/47258455/c09c3136-38a3-450a-8c93-46261a1b3a94)

I know the live example of the web app shows the symbols so I'm sure that this is something simple but I don’t see any calls in the example that might rectify getting the symbols to show in my web app.

Thanks, Rick

**Comment by timmaffett** [comment]
The current stable web version of the flutter engine has a bug in icon tree
shaking that can corrupt the output fonts.  You can turn off icon tree
shaking when you build and see if that helps.  This may be something else
though..   can you name a small example app that demonstrates the problem ?
(Or if your app is open source that would fine also).
   (Btw my fix for the flutter engine is in master and may be in the beta
branch now also, I think you can find reference to the pr# here somewhere,
again not at my computer so I can't look that up readily)

-tim

**Comment by pt-rick** [comment]
Ah - perhaps that's the issue. I'm using Flutter 3.7.11 (Dart 2.19.6) stable since we have yet to move our application to null safety. I did try and rebuild the web app using --no-tree-shake-icons, but the symbol icons are still not showing in the web app. Our app isn't open source but the use of the icons is very simple - I have a map of strings to IconData and use the string as the key and pass the resulting IconData into a Flutter Icon. In the image I attached earlier, the icons that are displaying are Icons (e.g. Icons.tv) and the ones failing are Symbols (e.g. Symbols.tv_with_assistant).  Just passing a symbol icon into Icon would be equivalent.

**Comment by timmaffett** [comment]
So basically no Symbols.XXX icons are working on your web version ?  That
might help figure this out - it sounds like the fonts themselves are not
working at all..

**Comment by pt-rick** [comment]
Correct - no Symbols are working in the web. They are fine on the Android, and, I'm assuming ,the iOS, side. I haven't tried iOS yet.

**Comment by pt-rick** [comment]
Quick update. I migrated our app to null safety and the symbols now work across our platforms.

**Comment by timmaffett** [comment]
@pt-rick  That's great news!

btw. I should be making a new release this week.
