### ISSUE TITLE
Missing import 'package:material_symbols_icons/symbols.dart'

### ISSUE THREAD

**Issue by woodmicha** [timmaffett/material_symbols_icons#14]
Must be doing something simple wrong as I'm unable to import 'package:material_symbols_icons/symbols.dart' after installing via flutter pub add material_symbols_icons.  The main import 'package:material_symbols_icons/material_symbols_icons.dart' works.

The version added to my project is ^4.39.1 as the 4.2711.0 doesn't install due to a dart sdk issue:

Because strive_ai_client depends on material_symbols_icons >=4.39.2 which requires SDK version >=2.19.0 <4.0.0, version solving failed.
pub get failed (1; Because strive_ai_client depends on material_symbols_icons >=4.39.2 which requires SDK version >=2.19.0 <4.0.0, version solving failed.) 

I'm running the following versions via VS Code Extensions
Dart v3.76.1 
Flutter v3.76.0

Perhaps I need to do the generator step?  Thanks in advance for any guidance.

Regards, Mike

**Comment by woodmicha** [comment]
I was able to resolve by upgrading flutter tools on my laptop and reinstalling the library.   symbols.dart is now installed and the version is 4.2711.0 which seems right.

**Comment by woodmicha** [comment]
Closing as it's working great!  Thanks for putting time into this library.

**Comment by timmaffett** [comment]
That's great Mike, I am glad you got it figured out!
