### ISSUE TITLE
Wrong import path separator used in readme example

### ISSUE THREAD

**Issue by dhafinrayhan** [timmaffett/material_symbols_icons#18]
In the readme, the example code for importing the package is:
```dart
import 'material_symbols_icons\symbols.dart'
```

This is wrong, because Dart imports use slash (`/`) rather than backslash (`\`).

Thanks to user [MendelG](https://stackoverflow.com/users/12349734/mendelg) in [stackoverflow.com](https://stackoverflow.com/) for [figuring out](https://stackoverflow.com/a/77903659/13625293).

**Comment by timmaffett** [comment]
Great catch.  It is also missing the 'package:' prefix.  I merged you pull request and added the `package:` as well.

Thanks!
