### ISSUE TITLE
Absence of "keep off" symbol

### ISSUE THREAD

**Issue by anthonymoretti** [timmaffett/material_symbols_icons#20]
Thanks for the package!
Symbol for ["keep off"](https://fonts.google.com/icons?icon.platform=ios&icon.set=Material+Symbols&icon.query=keep+off) is missing.

**Comment by timmaffett** [comment]
Thanks for discovering this and reporting it!!
In investigating this I discovered that the `keep_off` (and `keep_public` and `keep`) icons seem to be entirely missing from the source material symbols fonts source .ttf files.

 I have filed a [bug report](https://github.com/google/material-design-icons/issues/1706) issue for this in the material symbols variable font repo and as soon as it is corrected I will release a new version of the package!

**Comment by timmaffett** [comment]
@anthonymoretti They have finally fixed the release pipeline bug in the official material symbols font repo and I have been able to release a new version of the package that is up to date with the currently available icons in the official repo!

**Comment by anthonymoretti** [comment]
Thank you very much. I confirm the symbol I wanted is there now. Much appreciated 👏
