### ISSUE TITLE
Missing Icons: contextual_token, contextual_token_add

### ISSUE THREAD

**Issue by AkanshDivker** [timmaffett/material_symbols_icons#26]
These icons are available for viewing in Google Fonts but not available in the package. Would appreciate if they could be added!

**Comment by timmaffett** [comment]
Thanks @AkanshDivker .  These fonts are missing from the official ttf variable fonts that are used to create the package.  I have filed an issue https://github.com/google/material-design-icons/issues/1719 to get to the bottom of why they are missing.

There had been some problems in the automated pipeline that creates these fonts and I thought it was all resolved, but obviously there are some icons that are still being missed.  It may be that they are just really new icons and that with Google I/O this today/week they have not been pushed out yet.

**Comment by timmaffett** [comment]
@AkanshDivker  The official repo has been updated and I have just pushed a new version to pub.dev  The only new icons were contextual_token and contextual_token_add and they are now be available in 4.2744.0

Thanks for the report!
