### ISSUE TITLE
more_horiz and more_vert seem smaller

### ISSUE THREAD

**Issue by jellynoone** [timmaffett/material_symbols_icons#28]
First thank you for an awesome package!

Second looking at icons:
- `more_horiz`
- `more_vert`
These seem to render smaller than what Google Fonts displays at: https://fonts.google.com/icons?icon.query=more_horiz&icon.set=Material+Symbols for the same settings

Attaching screenshots from your example website and Google Fonts.
<img width="364" alt="Screenshot example" src="https://github.com/timmaffett/material_symbols_icons/assets/77585130/7a3638ae-db2d-441b-a886-e4d8488a3225">
<img width="466" alt="Screenshot Google Fonts" src="https://github.com/timmaffett/material_symbols_icons/assets/77585130/6dad367b-80a2-496b-9e7c-a09b9731871c">

**Comment by timmaffett** [comment]
I suspect that @tphinney may have changed this in the most recent google fonts version and it has not made it to the material symbols repo yet.
https://github.com/google/material-design-icons/blob/master/symbols/web/more_horiz/materialsymbolsoutlined/more_horiz_grad200fill1_48px.svg

this svg was update May 4, 2024 and has the 'wider' stance.  
The changes make it to the google font website before they make it to the material symbols repo (where I pull the fonts from).
With luck we will see the change to these icons when the next version is pushed to the repo,

**Comment by jellynoone** [comment]
Thank you @timmaffett for the quick response, I just double checked this and it was my mistake.

I was looking at the fonts from different optical sizes. The material icons website has sets the default to 24, while your example uses 48. Thus the change.

Sorry for the noise.

**Comment by timmaffett** [comment]
Oh sweet.  This is a good find though and perhaps I need to change our default optical size to 24 as well to match the google fonts default.  I guess I have the optical size set to 48 because I am using 48px for the size and I wanted optical size to match.  I will check out the google fonts site and consider changing the defaults to match the settings there better.

I am going to close this.

**Comment by timmaffett** [comment]
Yes the google fonts site uses 48px for the icon display font-size and then 24 for the optical size default.  You are not able to adjust the icon font-size on their site.
I think it may be worthwhile to set the default for the example app to an optical size of 24px as well.

Thanks for submitting this issue @jellynoone !
