### ISSUE TITLE
Missing link to package pub.dev page in readme

### ISSUE THREAD

**Issue by guyluz11** [timmaffett/material_symbols_icons#5]
Please add a link to [pub.dev](https://pub.dev/packages/material_symbols_icons) page in readme for easy linking

![image](https://github.com/timmaffett/material_symbols_icons/assets/9304740/284b9d29-fdea-4d10-80b2-c844458e45a3)

**Comment by timmaffett** [comment]
Thanks @guyluz11 I have added he pub.dev link shield to the readme.
I have also released a new version that uses the latest version 2.662 of the material symbols icons variable fonts.
