### ISSUE TITLE
Absence of list of all icons

### ISSUE THREAD

**Issue by ProcnerKacper** [timmaffett/material_symbols_icons#6]
Hi, could you add the list of all icons divided by font family or just list all icons?

**Comment by timmaffett** [comment]
Hi @ProcnerKacper ,
   In the example app found [here ( https://timmaffett.github.io/material_symbols_icons/ )](https://timmaffett.github.io/material_symbols_icons/) you can find browse/search for icons.

The [symbols_map.dart file](https://github.com/timmaffett/material_symbols_icons/blob/master/example/lib/symbols_map.dart) has a list map of all the icons by name.

Is there another way you would also like this presented ?

**Comment by ProcnerKacper** [comment]
Hi @timmaffett ,
This is exactly what I have done, but it will be inconvenient when You add more or change icons, so I need to redo it on the package update. This is where my suggestion comes from.

**Comment by timmaffett** [comment]
Are you suggesting that I add the list to the end of the readme, or at another text file that has the list so you can see the changes that are made to that file with each update?
Within the raw fonts directory there's a icons-unicode.txt file which has a list of all icon names and their code points.  There is also a subdirectoy called LAST_VERSION which holds previous versions of that file. You can dip these files to see the changes that been made between versions.
   Perhaps I could start adding a summary to the change log or another file that lists the additions and subtractions.
I'm on my phone currently so forgive any errors in this text

**Comment by ProcnerKacper** [comment]
Sorry for not getting back to you sooner. What I mean is that having it in the package would be nice  that have access to the list of all icons instead of doing it manually in every project, as you show In the (https://github.com/timmaffett/material_symbols_icons/blob/master/example/lib/symbols_map.dart) 
so basically, to move this file to package content and expose it

**Comment by timmaffett** [comment]
Hi @ProcnerKacper - The reason that I did not include the `symbols_map.dart` file from the example app within the main package is that I was afraid it would create references to every icon and prevent tree-shaking from being able to determine which icons are being used by an app using the package. 
  It may be that including the file in the package \lib directory, and have it not be included implicitly, will not trigger references and prevent tree-shaking from working.   I would have to explore that when/if I have time.   You are welcome to test this yourself and submit a PR.
  (and of course you are free to copy that file and include it in your own app.)

**Comment by timmaffett** [comment]
A map of all iconnames to unicode code points is now included in the package.
Please see https://github.com/timmaffett/material_symbols_icons/issues/16 for details.

I am closing this issue - feel free to re-open it if this is not a workable solution for you!
